/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useGLTF, 

 } from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/hatchback/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
<mesh geometry={nodes.Mesh_wheel_frontLeft032.geometry} material={nodes.Mesh_wheel_frontLeft032.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft032_1.geometry} material={nodes.Mesh_wheel_frontLeft032_1.material} />
<mesh geometry={nodes.Mesh_body013.geometry} material={materials['plastic.001']} />
<mesh geometry={nodes.Mesh_body013_1.geometry} material={materials['paintGreen.001']} />
<mesh geometry={nodes.Mesh_body013_2.geometry} material={materials['lightFront.001']} />
<mesh geometry={nodes.Mesh_body013_3.geometry} material={materials['_defaultMat.001']} />
<mesh geometry={nodes.Mesh_body013_4.geometry} material={materials['window.001']} />
<mesh geometry={nodes.Mesh_body013_5.geometry} material={materials['lightBack.001']} />
<mesh geometry={nodes.Mesh_wheel_frontLeft031.geometry} material={nodes.Mesh_wheel_frontLeft031.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft031_1.geometry} material={nodes.Mesh_wheel_frontLeft031_1.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft010.geometry} material={nodes.Mesh_wheel_frontLeft010.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft010_1.geometry} material={nodes.Mesh_wheel_frontLeft010_1.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft009.geometry} material={nodes.Mesh_wheel_frontLeft009.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft009_1.geometry} material={nodes.Mesh_wheel_frontLeft009_1.material} />

    </group>
  )
}

useGLTF.preload('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/hatchback/model.gltf')